-- Seed Data for Swagruha Foods

INSERT INTO public.products (id, name_en, name_te, slug, description_en, description_te, category, images, ingredients_en, ingredients_te, price, compare_price, stock, weight, sku, is_active)
VALUES 
(
      gen_random_uuid(), 
      'Andhra Avakaya', 
      'ఆంధ్ర అవకాయ', 
      'andhra-avakaya-250g', 
      'The king of all pickles! Our Andhra Avakaya is made with raw mangoes, mustard seeds, red chilli powder, salt, and sesame oil — just like Amma makes it. Bold, spicy, and utterly addictive.', 
      'అన్ని ఊరగాయలలో రాజు! మా ఆంధ్ర అవకాయ పచ్చి మామిడికాయలు, ఆవాలు, ఎర్ర మిర్చి పొడి, ఉప్పు మరియు నువ్వుల నూనెతో తయారు చేయబడింది — అమ్మ తయారు చేసిన విధంగా.', 
      'pickles', 
      '{"/images/pickle.jpg"}', 
      'Raw Mango, Mustard Seeds, Red Chilli Powder, Salt, Sesame Oil, Fenugreek', 
      'పచ్చి మామిడికాయ, ఆవాలు, ఎర్ర మిర్చి పొడి, ఉప్పు, నువ్వుల నూనె, మెంతులు', 
      180, 
      220, 
      50, 
      '250g', 
      'SSF-AVK-250', 
      true
    ),
(
      gen_random_uuid(), 
      'Andhra Avakaya', 
      'ఆంధ్ర అవకాయ', 
      'andhra-avakaya-500g', 
      'The king of all pickles! Our Andhra Avakaya is made with raw mangoes, mustard seeds, red chilli powder, salt, and sesame oil — just like Amma makes it. Bold, spicy, and utterly addictive.', 
      'అన్ని ఊరగాయలలో రాజు! మా ఆంధ్ర అవకాయ పచ్చి మామిడికాయలు, ఆవాలు, ఎర్ర మిర్చి పొడి, ఉప్పు మరియు నువ్వుల నూనెతో తయారు చేయబడింది — అమ్మ తయారు చేసిన విధంగా.', 
      'pickles', 
      '{"/images/pickle.jpg"}', 
      'Raw Mango, Mustard Seeds, Red Chilli Powder, Salt, Sesame Oil, Fenugreek', 
      'పచ్చి మామిడికాయ, ఆవాలు, ఎర్ర మిర్చి పొడి, ఉప్పు, నువ్వుల నూనె, మెంతులు', 
      320, 
      400, 
      30, 
      '500g', 
      'SSF-AVK-500', 
      true
    ),
(
      gen_random_uuid(), 
      'Andhra Avakaya', 
      'ఆంధ్ర అవకాయ', 
      'andhra-avakaya-1kg', 
      'The king of all pickles! Our Andhra Avakaya is made with raw mangoes, mustard seeds, red chilli powder, salt, and sesame oil — just like Amma makes it. Bold, spicy, and utterly addictive.', 
      'అన్ని ఊరగాయలలో రాజు! మా ఆంధ్ర అవకాయ పచ్చి మామిడికాయలు, ఆవాలు, ఎర్ర మిర్చి పొడి, ఉప్పు మరియు నువ్వుల నూనెతో తయారు చేయబడింది — అమ్మ తయారు చేసిన విధంగా.', 
      'pickles', 
      '{"/images/pickle.jpg"}', 
      'Raw Mango, Mustard Seeds, Red Chilli Powder, Salt, Sesame Oil, Fenugreek', 
      'పచ్చి మామిడికాయ, ఆవాలు, ఎర్ర మిర్చి పొడి, ఉప్పు, నువ్వుల నూనె, మెంతులు', 
      600, 
      750, 
      20, 
      '1kg', 
      'SSF-AVK-1KG', 
      true
    ),
(
      gen_random_uuid(), 
      'Gongura Pickle', 
      'గోంగూర పచ్చడి', 
      'gongura-pickle-250g', 
      'The pride of Andhra! Our Gongura (Sorrel leaves) pickle is tangy, spicy, and deeply flavorful. Made with freshly sourced gongura leaves, mustard, fenugreek and red chillies.', 
      'ఆంధ్ర గర్వం! మా గోంగూర పచ్చడి పులుపుగా, కారంగా, అద్భుతమైన రుచితో ఉంటుంది. తాజా గోంగూర ఆకులు, ఆవాలు, మెంతులు మరియు ఎర్ర మిర్చిలతో తయారు చేయబడింది.', 
      'pickles', 
      '{"/images/pickle.jpg"}', 
      'Gongura Leaves, Red Chillies, Mustard Seeds, Fenugreek, Sesame Oil, Salt, Garlic', 
      'గోంగూర ఆకులు, ఎర్ర మిర్చులు, ఆవాలు, మెంతులు, నువ్వుల నూనె, ఉప్పు, వెల్లుల్లి', 
      160, 
      200, 
      40, 
      '250g', 
      'SSF-GON-250', 
      true
    ),
(
      gen_random_uuid(), 
      'Gongura Pickle', 
      'గోంగూర పచ్చడి', 
      'gongura-pickle-500g', 
      'The pride of Andhra! Our Gongura (Sorrel leaves) pickle is tangy, spicy, and deeply flavorful. Made with freshly sourced gongura leaves, mustard, fenugreek and red chillies.', 
      'ఆంధ్ర గర్వం! మా గోంగూర పచ్చడి పులుపుగా, కారంగా, అద్భుతమైన రుచితో ఉంటుంది. తాజా గోంగూర ఆకులు, ఆవాలు, మెంతులు మరియు ఎర్ర మిర్చిలతో తయారు చేయబడింది.', 
      'pickles', 
      '{"/images/pickle.jpg"}', 
      'Gongura Leaves, Red Chillies, Mustard Seeds, Fenugreek, Sesame Oil, Salt, Garlic', 
      'గోంగూర ఆకులు, ఎర్ర మిర్చులు, ఆవాలు, మెంతులు, నువ్వుల నూనె, ఉప్పు, వెల్లుల్లి', 
      290, 
      360, 
      25, 
      '500g', 
      'SSF-GON-500', 
      true
    ),
(
      gen_random_uuid(), 
      'Gongura Pickle', 
      'గోంగూర పచ్చడి', 
      'gongura-pickle-1kg', 
      'The pride of Andhra! Our Gongura (Sorrel leaves) pickle is tangy, spicy, and deeply flavorful. Made with freshly sourced gongura leaves, mustard, fenugreek and red chillies.', 
      'ఆంధ్ర గర్వం! మా గోంగూర పచ్చడి పులుపుగా, కారంగా, అద్భుతమైన రుచితో ఉంటుంది. తాజా గోంగూర ఆకులు, ఆవాలు, మెంతులు మరియు ఎర్ర మిర్చిలతో తయారు చేయబడింది.', 
      'pickles', 
      '{"/images/pickle.jpg"}', 
      'Gongura Leaves, Red Chillies, Mustard Seeds, Fenugreek, Sesame Oil, Salt, Garlic', 
      'గోంగూర ఆకులు, ఎర్ర మిర్చులు, ఆవాలు, మెంతులు, నువ్వుల నూనె, ఉప్పు, వెల్లుల్లి', 
      550, 
      700, 
      15, 
      '1kg', 
      'SSF-GON-1KG', 
      true
    ),
(
      gen_random_uuid(), 
      'Lemon Pickle', 
      'నిమ్మకాయ ఊరగాయ', 
      'lemon-pickle-250g', 
      'Sunshine in a jar! Our Lemon Pickle is perfectly balanced with tangy lemon, spicy chillies, and aromatic spices. A perfect accompaniment to rice, chapati, or snacks.', 
      'జాడీలో సూర్యకిరణం! మా నిమ్మకాయ ఊరగాయ పులుపైన నిమ్మకాయ, కారమైన మిర్చులు మరియు సుగంధ మసాలాలతో సరిగ్గా సమతుల్యంగా ఉంటుంది.', 
      'pickles', 
      '{"/images/pickle.jpg"}', 
      'Lemon, Red Chilli Powder, Salt, Mustard Seeds, Sesame Oil, Fenugreek, Asafoetida', 
      'నిమ్మకాయ, ఎర్ర మిర్చి పొడి, ఉప్పు, ఆవాలు, నువ్వుల నూనె, మెంతులు, ఇంగువ', 
      140, 
      170, 
      60, 
      '250g', 
      'SSF-LEM-250', 
      true
    ),
(
      gen_random_uuid(), 
      'Lemon Pickle', 
      'నిమ్మకాయ ఊరగాయ', 
      'lemon-pickle-500g', 
      'Sunshine in a jar! Our Lemon Pickle is perfectly balanced with tangy lemon, spicy chillies, and aromatic spices. A perfect accompaniment to rice, chapati, or snacks.', 
      'జాడీలో సూర్యకిరణం! మా నిమ్మకాయ ఊరగాయ పులుపైన నిమ్మకాయ, కారమైన మిర్చులు మరియు సుగంధ మసాలాలతో సరిగ్గా సమతుల్యంగా ఉంటుంది.', 
      'pickles', 
      '{"/images/pickle.jpg"}', 
      'Lemon, Red Chilli Powder, Salt, Mustard Seeds, Sesame Oil, Fenugreek, Asafoetida', 
      'నిమ్మకాయ, ఎర్ర మిర్చి పొడి, ఉప్పు, ఆవాలు, నువ్వుల నూనె, మెంతులు, ఇంగువ', 
      260, 
      320, 
      35, 
      '500g', 
      'SSF-LEM-500', 
      true
    ),
(
      gen_random_uuid(), 
      'Tomato Pickle', 
      'టమాటా పచ్చడి', 
      'tomato-pickle-250g', 
      'A Telugu kitchen staple! This rich and tangy tomato pickle is cooked with fresh tomatoes, mustard, and a blend of aromatic spices that make every meal special.', 
      'తెలుగు వంటింటి అవసరం! ఈ రిచ్ మరియు పులుపైన టమాటా పచ్చడి తాజా టమాటాలు, ఆవాలు మరియు సుగంధ మసాలాల మిశ్రమంతో వండబడుతుంది.', 
      'pickles', 
      '{"/images/pickle.jpg"}', 
      'Tomatoes, Red Chillies, Mustard Seeds, Sesame Oil, Salt, Garlic, Curry Leaves', 
      'టమాటాలు, ఎర్ర మిర్చులు, ఆవాలు, నువ్వుల నూనె, ఉప్పు, వెల్లుల్లి, కరివేపాకు', 
      130, 
      160, 
      45, 
      '250g', 
      'SSF-TOM-250', 
      true
    ),
(
      gen_random_uuid(), 
      'Tomato Pickle', 
      'టమాటా పచ్చడి', 
      'tomato-pickle-500g', 
      'A Telugu kitchen staple! This rich and tangy tomato pickle is cooked with fresh tomatoes, mustard, and a blend of aromatic spices that make every meal special.', 
      'తెలుగు వంటింటి అవసరం! ఈ రిచ్ మరియు పులుపైన టమాటా పచ్చడి తాజా టమాటాలు, ఆవాలు మరియు సుగంధ మసాలాల మిశ్రమంతో వండబడుతుంది.', 
      'pickles', 
      '{"/images/pickle.jpg"}', 
      'Tomatoes, Red Chillies, Mustard Seeds, Sesame Oil, Salt, Garlic, Curry Leaves', 
      'టమాటాలు, ఎర్ర మిర్చులు, ఆవాలు, నువ్వుల నూనె, ఉప్పు, వెల్లుల్లి, కరివేపాకు', 
      240, 
      300, 
      28, 
      '500g', 
      'SSF-TOM-500', 
      true
    ),
(
      gen_random_uuid(), 
      'Kandi Karam', 
      'కంది కారం', 
      'kandi-karam-100g', 
      'The heart of Telugu breakfasts! Kandi Karam made with roasted toor dal, red chillies, garlic, and cumin. Perfect with idli, dosa, or rice and ghee.', 
      'తెలుగు అల్పాహారాల హృదయం! వేయించిన కంది పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి మరియు జీలకర్రతో తయారు చేసిన కంది కారం. ఇడ్లీ, దోశ లేదా అన్నం మరియు నెయ్యితో సరిపోతుంది.', 
      'karam', 
      '{"/images/karam.jpg"}', 
      'Toor Dal, Red Chillies, Garlic, Cumin, Salt, Curry Leaves, Asafoetida', 
      'కంది పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి, జీలకర్ర, ఉప్పు, కరివేపాకు, ఇంగువ', 
      80, 
      100, 
      80, 
      '100g', 
      'SSF-KKR-100', 
      true
    ),
(
      gen_random_uuid(), 
      'Kandi Karam', 
      'కంది కారం', 
      'kandi-karam-250g', 
      'The heart of Telugu breakfasts! Kandi Karam made with roasted toor dal, red chillies, garlic, and cumin. Perfect with idli, dosa, or rice and ghee.', 
      'తెలుగు అల్పాహారాల హృదయం! వేయించిన కంది పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి మరియు జీలకర్రతో తయారు చేసిన కంది కారం. ఇడ్లీ, దోశ లేదా అన్నం మరియు నెయ్యితో సరిపోతుంది.', 
      'karam', 
      '{"/images/karam.jpg"}', 
      'Toor Dal, Red Chillies, Garlic, Cumin, Salt, Curry Leaves, Asafoetida', 
      'కంది పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి, జీలకర్ర, ఉప్పు, కరివేపాకు, ఇంగువ', 
      180, 
      220, 
      50, 
      '250g', 
      'SSF-KKR-250', 
      true
    ),
(
      gen_random_uuid(), 
      'Kandi Karam', 
      'కంది కారం', 
      'kandi-karam-500g', 
      'The heart of Telugu breakfasts! Kandi Karam made with roasted toor dal, red chillies, garlic, and cumin. Perfect with idli, dosa, or rice and ghee.', 
      'తెలుగు అల్పాహారాల హృదయం! వేయించిన కంది పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి మరియు జీలకర్రతో తయారు చేసిన కంది కారం. ఇడ్లీ, దోశ లేదా అన్నం మరియు నెయ్యితో సరిపోతుంది.', 
      'karam', 
      '{"/images/karam.jpg"}', 
      'Toor Dal, Red Chillies, Garlic, Cumin, Salt, Curry Leaves, Asafoetida', 
      'కంది పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి, జీలకర్ర, ఉప్పు, కరివేపాకు, ఇంగువ', 
      320, 
      400, 
      30, 
      '500g', 
      'SSF-KKR-500', 
      true
    ),
(
      gen_random_uuid(), 
      'Idli Karam', 
      'ఇడ్లీ కారం', 
      'idli-karam-100g', 
      'The ultimate idli companion! Our Idli Karam is a perfect blend of roasted chana dal, red chillies, garlic, and spices. Just a pinch with oil or ghee transforms your idli.', 
      'ఇడ్లీకి అత్యుత్తమ జోడీ! మా ఇడ్లీ కారం వేయించిన శెనగ పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి మరియు మసాలాల పరిపూర్ణ మిశ్రమం.', 
      'karam', 
      '{"/images/karam.jpg"}', 
      'Chana Dal, Red Chillies, Garlic, Cumin, Salt, Sesame Seeds, Curry Leaves', 
      'శెనగ పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి, జీలకర్ర, ఉప్పు, నువ్వులు, కరివేపాకు', 
      70, 
      90, 
      90, 
      '100g', 
      'SSF-IDK-100', 
      true
    ),
(
      gen_random_uuid(), 
      'Idli Karam', 
      'ఇడ్లీ కారం', 
      'idli-karam-250g', 
      'The ultimate idli companion! Our Idli Karam is a perfect blend of roasted chana dal, red chillies, garlic, and spices. Just a pinch with oil or ghee transforms your idli.', 
      'ఇడ్లీకి అత్యుత్తమ జోడీ! మా ఇడ్లీ కారం వేయించిన శెనగ పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి మరియు మసాలాల పరిపూర్ణ మిశ్రమం.', 
      'karam', 
      '{"/images/karam.jpg"}', 
      'Chana Dal, Red Chillies, Garlic, Cumin, Salt, Sesame Seeds, Curry Leaves', 
      'శెనగ పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి, జీలకర్ర, ఉప్పు, నువ్వులు, కరివేపాకు', 
      160, 
      200, 
      55, 
      '250g', 
      'SSF-IDK-250', 
      true
    ),
(
      gen_random_uuid(), 
      'Idli Karam', 
      'ఇడ్లీ కారం', 
      'idli-karam-500g', 
      'The ultimate idli companion! Our Idli Karam is a perfect blend of roasted chana dal, red chillies, garlic, and spices. Just a pinch with oil or ghee transforms your idli.', 
      'ఇడ్లీకి అత్యుత్తమ జోడీ! మా ఇడ్లీ కారం వేయించిన శెనగ పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి మరియు మసాలాల పరిపూర్ణ మిశ్రమం.', 
      'karam', 
      '{"/images/karam.jpg"}', 
      'Chana Dal, Red Chillies, Garlic, Cumin, Salt, Sesame Seeds, Curry Leaves', 
      'శెనగ పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి, జీలకర్ర, ఉప్పు, నువ్వులు, కరివేపాకు', 
      290, 
      360, 
      35, 
      '500g', 
      'SSF-IDK-500', 
      true
    ),
(
      gen_random_uuid(), 
      'Curry Leaf Podi', 
      'కరివేపాకు పొడి', 
      'curry-leaf-podi-100g', 
      'Fragrant and nutritious! Our Curry Leaf Podi captures the earthy aroma and health benefits of fresh curry leaves combined with lentils and spices.', 
      'సుగంధమైన మరియు పోషకాహారం! మా కరివేపాకు పొడి తాజా కరివేపాకు యొక్క మట్టి వాసన మరియు ఆరోగ్య ప్రయోజనాలను పప్పు మరియు మసాలాలతో కలపుతుంది.', 
      'podi', 
      '{"/images/karam.jpg"}', 
      'Curry Leaves, Urad Dal, Chana Dal, Red Chillies, Garlic, Salt, Sesame Seeds', 
      'కరివేపాకు, మినప పప్పు, శెనగ పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి, ఉప్పు, నువ్వులు', 
      90, 
      110, 
      70, 
      '100g', 
      'SSF-CVP-100', 
      true
    ),
(
      gen_random_uuid(), 
      'Curry Leaf Podi', 
      'కరివేపాకు పొడి', 
      'curry-leaf-podi-250g', 
      'Fragrant and nutritious! Our Curry Leaf Podi captures the earthy aroma and health benefits of fresh curry leaves combined with lentils and spices.', 
      'సుగంధమైన మరియు పోషకాహారం! మా కరివేపాకు పొడి తాజా కరివేపాకు యొక్క మట్టి వాసన మరియు ఆరోగ్య ప్రయోజనాలను పప్పు మరియు మసాలాలతో కలపుతుంది.', 
      'podi', 
      '{"/images/karam.jpg"}', 
      'Curry Leaves, Urad Dal, Chana Dal, Red Chillies, Garlic, Salt, Sesame Seeds', 
      'కరివేపాకు, మినప పప్పు, శెనగ పప్పు, ఎర్ర మిర్చులు, వెల్లుల్లి, ఉప్పు, నువ్వులు', 
      200, 
      250, 
      45, 
      '250g', 
      'SSF-CVP-250', 
      true
    ),
(
      gen_random_uuid(), 
      'Peanut Podi', 
      'పల్లీ పొడి', 
      'peanut-podi-100g', 
      'Crunchy, nutty, and absolutely delicious! Our Peanut Podi is made from roasted peanuts, red chillies, garlic, and a touch of tamarind. Perfect with rice, dosa, or as a snack.', 
      'క్రంచీ, నట్టీ మరియు పూర్తిగా రుచికరం! మా పల్లీ పొడి వేయించిన వేరుశెనగలు, ఎర్ర మిర్చులు, వెల్లుల్లి మరియు చిన్న చింతపండుతో తయారు చేయబడింది.', 
      'podi', 
      '{"/images/karam.jpg"}', 
      'Roasted Peanuts, Red Chillies, Garlic, Tamarind, Salt, Cumin, Curry Leaves', 
      'వేయించిన వేరుశెనగలు, ఎర్ర మిర్చులు, వెల్లుల్లి, చింతపండు, ఉప్పు, జీలకర్ర, కరివేపాకు', 
      75, 
      95, 
      85, 
      '100g', 
      'SSF-PNP-100', 
      true
    ),
(
      gen_random_uuid(), 
      'Peanut Podi', 
      'పల్లీ పొడి', 
      'peanut-podi-250g', 
      'Crunchy, nutty, and absolutely delicious! Our Peanut Podi is made from roasted peanuts, red chillies, garlic, and a touch of tamarind. Perfect with rice, dosa, or as a snack.', 
      'క్రంచీ, నట్టీ మరియు పూర్తిగా రుచికరం! మా పల్లీ పొడి వేయించిన వేరుశెనగలు, ఎర్ర మిర్చులు, వెల్లుల్లి మరియు చిన్న చింతపండుతో తయారు చేయబడింది.', 
      'podi', 
      '{"/images/karam.jpg"}', 
      'Roasted Peanuts, Red Chillies, Garlic, Tamarind, Salt, Cumin, Curry Leaves', 
      'వేయించిన వేరుశెనగలు, ఎర్ర మిర్చులు, వెల్లుల్లి, చింతపండు, ఉప్పు, జీలకర్ర, కరివేపాకు', 
      170, 
      210, 
      50, 
      '250g', 
      'SSF-PNP-250', 
      true
    ),
(
      gen_random_uuid(), 
      'Peanut Podi', 
      'పల్లీ పొడి', 
      'peanut-podi-500g', 
      'Crunchy, nutty, and absolutely delicious! Our Peanut Podi is made from roasted peanuts, red chillies, garlic, and a touch of tamarind. Perfect with rice, dosa, or as a snack.', 
      'క్రంచీ, నట్టీ మరియు పూర్తిగా రుచికరం! మా పల్లీ పొడి వేయించిన వేరుశెనగలు, ఎర్ర మిర్చులు, వెల్లుల్లి మరియు చిన్న చింతపండుతో తయారు చేయబడింది.', 
      'podi', 
      '{"/images/karam.jpg"}', 
      'Roasted Peanuts, Red Chillies, Garlic, Tamarind, Salt, Cumin, Curry Leaves', 
      'వేయించిన వేరుశెనగలు, ఎర్ర మిర్చులు, వెల్లుల్లి, చింతపండు, ఉప్పు, జీలకర్ర, కరివేపాకు', 
      310, 
      390, 
      30, 
      '500g', 
      'SSF-PNP-500', 
      true
    ),
(
      gen_random_uuid(), 
      'Sambar Powder', 
      'సాంబార్ పొడి', 
      'sambar-powder-100g', 
      'The soul of South Indian cooking! Our Sambar Powder is a carefully balanced blend of 16 roasted spices that gives your sambar the authentic village restaurant taste.', 
      'దక్షిణ భారత వంటపాకం యొక్క ఆత్మ! మా సాంబార్ పొడి 16 వేయించిన మసాలాల జాగ్రత్తగా సమతుల్యమైన మిశ్రమం.', 
      'masala', 
      '{"/images/masala.jpg"}', 
      'Coriander, Cumin, Black Pepper, Red Chillies, Mustard, Fenugreek, Curry Leaves, Turmeric, Cinnamon, Cloves, Cardamom, Asafoetida', 
      'కొత్తిమీర, జీలకర్ర, నల్ల మిరియాలు, ఎర్ర మిర్చులు, ఆవాలు, మెంతులు, కరివేపాకు, పసుపు, దాల్చిన చెక్క, లవంగాలు, యాలకులు, ఇంగువ', 
      85, 
      105, 
      75, 
      '100g', 
      'SSF-SBP-100', 
      true
    ),
(
      gen_random_uuid(), 
      'Sambar Powder', 
      'సాంబార్ పొడి', 
      'sambar-powder-250g', 
      'The soul of South Indian cooking! Our Sambar Powder is a carefully balanced blend of 16 roasted spices that gives your sambar the authentic village restaurant taste.', 
      'దక్షిణ భారత వంటపాకం యొక్క ఆత్మ! మా సాంబార్ పొడి 16 వేయించిన మసాలాల జాగ్రత్తగా సమతుల్యమైన మిశ్రమం.', 
      'masala', 
      '{"/images/masala.jpg"}', 
      'Coriander, Cumin, Black Pepper, Red Chillies, Mustard, Fenugreek, Curry Leaves, Turmeric, Cinnamon, Cloves, Cardamom, Asafoetida', 
      'కొత్తిమీర, జీలకర్ర, నల్ల మిరియాలు, ఎర్ర మిర్చులు, ఆవాలు, మెంతులు, కరివేపాకు, పసుపు, దాల్చిన చెక్క, లవంగాలు, యాలకులు, ఇంగువ', 
      190, 
      240, 
      48, 
      '250g', 
      'SSF-SBP-250', 
      true
    ),
(
      gen_random_uuid(), 
      'Sambar Powder', 
      'సాంబార్ పొడి', 
      'sambar-powder-500g', 
      'The soul of South Indian cooking! Our Sambar Powder is a carefully balanced blend of 16 roasted spices that gives your sambar the authentic village restaurant taste.', 
      'దక్షిణ భారత వంటపాకం యొక్క ఆత్మ! మా సాంబార్ పొడి 16 వేయించిన మసాలాల జాగ్రత్తగా సమతుల్యమైన మిశ్రమం.', 
      'masala', 
      '{"/images/masala.jpg"}', 
      'Coriander, Cumin, Black Pepper, Red Chillies, Mustard, Fenugreek, Curry Leaves, Turmeric, Cinnamon, Cloves, Cardamom, Asafoetida', 
      'కొత్తిమీర, జీలకర్ర, నల్ల మిరియాలు, ఎర్ర మిర్చులు, ఆవాలు, మెంతులు, కరివేపాకు, పసుపు, దాల్చిన చెక్క, లవంగాలు, యాలకులు, ఇంగువ', 
      350, 
      440, 
      28, 
      '500g', 
      'SSF-SBP-500', 
      true
    ),
(
      gen_random_uuid(), 
      'Chicken Masala', 
      'చికెన్ మసాలా', 
      'chicken-masala-100g', 
      'Restaurant-quality at home! Our Andhra-style Chicken Masala brings the bold, fiery flavors of Telugu cooking to your kitchen. Made with premium whole spices, slow roasted to perfection.', 
      'ఇంట్లో రెస్టారెంట్ నాణ్యత! మా ఆంధ్ర స్టైల్ చికెన్ మసాలా తెలుగు వంట యొక్క బోల్డ్, ఫైరీ రుచులను మీ వంటింటికి తీసుకువస్తుంది.', 
      'masala', 
      '{"/images/masala.jpg"}', 
      'Red Chillies, Coriander, Cumin, Black Pepper, Cinnamon, Cloves, Cardamom, Fennel, Star Anise, Turmeric, Mace, Nutmeg', 
      'ఎర్ర మిర్చులు, కొత్తిమీర, జీలకర్ర, నల్ల మిరియాలు, దాల్చిన చెక్క, లవంగాలు, యాలకులు, సోంపు, స్టార్ అనిస్, పసుపు, జాపత్రి, జాజికాయ', 
      120, 
      150, 
      60, 
      '100g', 
      'SSF-CHM-100', 
      true
    ),
(
      gen_random_uuid(), 
      'Chicken Masala', 
      'చికెన్ మసాలా', 
      'chicken-masala-200g', 
      'Restaurant-quality at home! Our Andhra-style Chicken Masala brings the bold, fiery flavors of Telugu cooking to your kitchen. Made with premium whole spices, slow roasted to perfection.', 
      'ఇంట్లో రెస్టారెంట్ నాణ్యత! మా ఆంధ్ర స్టైల్ చికెన్ మసాలా తెలుగు వంట యొక్క బోల్డ్, ఫైరీ రుచులను మీ వంటింటికి తీసుకువస్తుంది.', 
      'masala', 
      '{"/images/masala.jpg"}', 
      'Red Chillies, Coriander, Cumin, Black Pepper, Cinnamon, Cloves, Cardamom, Fennel, Star Anise, Turmeric, Mace, Nutmeg', 
      'ఎర్ర మిర్చులు, కొత్తిమీర, జీలకర్ర, నల్ల మిరియాలు, దాల్చిన చెక్క, లవంగాలు, యాలకులు, సోంపు, స్టార్ అనిస్, పసుపు, జాపత్రి, జాజికాయ', 
      220, 
      275, 
      40, 
      '200g', 
      'SSF-CHM-200', 
      true
    ),
(
      gen_random_uuid(), 
      'Chicken Masala', 
      'చికెన్ మసాలా', 
      'chicken-masala-500g', 
      'Restaurant-quality at home! Our Andhra-style Chicken Masala brings the bold, fiery flavors of Telugu cooking to your kitchen. Made with premium whole spices, slow roasted to perfection.', 
      'ఇంట్లో రెస్టారెంట్ నాణ్యత! మా ఆంధ్ర స్టైల్ చికెన్ మసాలా తెలుగు వంట యొక్క బోల్డ్, ఫైరీ రుచులను మీ వంటింటికి తీసుకువస్తుంది.', 
      'masala', 
      '{"/images/masala.jpg"}', 
      'Red Chillies, Coriander, Cumin, Black Pepper, Cinnamon, Cloves, Cardamom, Fennel, Star Anise, Turmeric, Mace, Nutmeg', 
      'ఎర్ర మిర్చులు, కొత్తిమీర, జీలకర్ర, నల్ల మిరియాలు, దాల్చిన చెక్క, లవంగాలు, యాలకులు, సోంపు, స్టార్ అనిస్, పసుపు, జాపత్రి, జాజికాయ', 
      500, 
      625, 
      20, 
      '500g', 
      'SSF-CHM-500', 
      true
    );
